### PR TITLE
feat(diagram): add ability to animate layout changes

### PR DESCRIPTION
**Pull request by danzrou**
This PR introduces an ability to animate layout changes, specifically to positioning (x,y) and zoom.
Usage example:

```ts
// Not passing anything, using default values of { timing: 200, easing: 'ease-in-out' }
zoomToFit() {
    this.diagramModel.animate(() => this.diagram?.zoomToFit());
}

// Passing a custom config
zoomToFit() {
    this.diagramModel.animate(() => this.diagram?.zoomToFit(), {
      timing: 500,
      easing: 'ease-out',
    });
}
```

### CODE REVIEW

**Review by DanielNetzeriAm — CHANGES_REQUESTED** [review]
Looking at the animation solution it seems like there's possibility for layout thrashing with the timeouts, also the current implementation of wrapping the diagrams functions we want to animate isn't natural, and perhaps animating specific functionality such as ZoomToCenter, ZoomToFit, ZoomToNode, etc... is the right way to do that.

**Comment by danzrou** [comment]
So you want it to participate only in those specific methods?
e.g. `zoomToFit(50, { timing: 500 })` ?

**Comment by DanielNetzeriAm** [comment]
> So you want it to participate only in those specific methods?
> e.g. `zoomToFit(50, { timing: 500 })` ?

feels more intuitive to animate those animation based functions using default values, as suggested by you above, and having the ability to overwrite the animation config.

**Comment by danzrou** [comment]
I'll think of something better.

**Pull request closed without merging**
